---
title: "First Knit"
author: "Issa Darrouj"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
I attended high school in the UAE and graduated in 2022. English, in my opinion, is easier than math, as it only makes us do essays. I did the best in chemistry.  

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
I have a Windows Legion, but I am not sure about the properties, but it is new. On a scale of 1 to 10, I would say 6. I would say it's not bad.  
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
I prefer that people call me by my first name (Issa), as it makes it simple and respectful. I also don't have any nicknames and have been called Issa my entire life.  
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
My main goal is to hopefully become an eye doctor (optometrist). The college subjects that are of the greatest interest to me are biology and chemistry. I am also aiming to get my bachelor's and master's degrees.   
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
Yes, I have traveled to Jordan and the UAE. I have not been in the military, but if I were to join, I would choose the Marines because they are known for their strength and discipline.   
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
No, I did not take Math 115 or Math 116 before. I did not know that Math 115 only satisfies a general education requirement, but I did know that Math 116 counts as statistics for several transfer institutions. That is why I am taking Math 116, mainly to transfer to UCLA. My plan is to earn an A grade so I do not upset my future plans.  
   
 






  




